### PR TITLE
Adjusting the number of rows and columns

### PR DESCRIPTION
**Pull request by lcristianiim**

### CODE REVIEW

**Comment by IonicaBizau** [comment]
Don't tell me this fixed the issue! :smile:

**Comment by lcristianiim** [comment]
Well it seems it did fixed it :smile: 
Also with https://github.com/jillix/service/commit/3a1f2a293335a398d5ab73ee9f5b2c1664ea7862

**Comment by IonicaBizau** [comment]
@lcristianiim And is the terminal now really full-width? If so, that's :cool: :tada:

**Comment by lcristianiim** [comment]
@IonicaBizau Yes now the terminal is full-width :yum:

**Comment by IonicaBizau** [comment]
Fix landing in web-term as well: https://github.com/IonicaBizau/web-term/pull/15 :tada: Looks awesome!

**Pull request merged**
